// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@footballstats.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/scrape/xgstats": {
            "post": {
                "description": "Scrape xG statistics and shot map data from xgstat.com",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Scrape xG shot map data",
                "parameters": [
                    {
                        "description": "Scrape request with xgstat.com URL",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scraped xG statistics and shot map data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/example_hello_internal_domain.DBXGStatFixture"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.Response"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.Response"
                        }
                    }
                }
            }
        },
        "/xgstats": {
            "get": {
                "description": "Retrieve saved xG statistics and shot map data from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Get xG statistics by fixture ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fixture ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retrieved xG statistics",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/example_hello_internal_domain.DBXGStatFixture"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.Response"
                        }
                    },
                    "404": {
                        "description": "Fixture not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example_hello_internal_domain.DBXGStatFixture": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer"
                },
                "away_shots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_hello_internal_domain.DBXGStatShot"
                    }
                },
                "away_team": {
                    "type": "string"
                },
                "away_xg": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "gameweek": {
                    "type": "integer"
                },
                "home_score": {
                    "type": "integer"
                },
                "home_shots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_hello_internal_domain.DBXGStatShot"
                    }
                },
                "home_team": {
                    "type": "string"
                },
                "home_xg": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "example_hello_internal_domain.DBXGStatShot": {
            "type": "object",
            "properties": {
                "is_goal": {
                    "type": "boolean"
                },
                "minute": {
                    "type": "integer"
                },
                "player_name": {
                    "type": "string"
                },
                "shot_type": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "xg": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "internal_api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.ScrapeRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Football Stats Scraper API",
	Description:      "A lightweight API for scraping football data from websites",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
