name: Football stats go CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/football-stats-go:${{ github.sha }} \
               -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/football-stats-go:latest .

      - name: Push Docker image with commit SHA tag
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/football-stats-go:${{ github.sha }}

      - name: Push Docker image with latest tag
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/football-stats-go:latest