name: Football stats go CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: go vet ./...
        
      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...